apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    namespace: nginx-ingress-controller
    server: {{ .Values.spec.destination.server }}
    helm:
      releaseName: nginx-ingress-controller
  project: default
  source:
    path: argocd/nginx-ingress-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
