apiVersion: v1
kind: Namespace
metadata:
  name: helm-guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
# example ns || should be removed or moved to another argocd app
# to which it is related by context
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
